### ISSUE TITLE
[Bug]Groups without search results after searching will not appear again when searching again

### ISSUE THREAD

**Issue by changshou83** [xiaoluoboding/vue-command-palette#14]
Taking the official website as an example, when entering `t`, the search results are `Raycast` and `Toggle Dark Mode`. Entering `o` again leaves only one result `Toggle Dark Mode`, but when `o` is deleted, `Raycast` does not appear in the result.

I suspect it was caused by `initStore` in `debouncedEmit` in `CommandRoot.vue`.

**Comment by xiaoluoboding** [comment]
fixed in #16
