### ISSUE TITLE
重复多次打开后，command-dialog-body内容会跳动，打开的次数越多，跳动的次数越多

### ISSUE THREAD

**Issue by zhaoeryu** [xiaoluoboding/vue-command-palette#18]
出现bug的效果如下👇

![屏幕录制2023-09-20 16 15 28](https://github.com/xiaoluoboding/vue-command-palette/assets/49333146/4bf55f20-60ca-42e8-8996-9aab7e3f36b1)

**Comment by xiaoluoboding** [comment]
感谢反馈

**Comment by zhaoeryu** [comment]
效率真高，目前测试没有出现该问题了
