### ISSUE TITLE
How to use this? 

### ISSUE THREAD

**Issue by HuakunShen** [xiaoluoboding/vue-command-palette#25]
The demo website looks great but how to get it to work like that? Do I have to write all css myself or is there a preset. 

This is what I get with the sample code.
![image](https://github.com/xiaoluoboding/vue-command-palette/assets/33727687/a005f479-e293-45ca-978d-baa8a6ecdb1a)

**Comment by acirinelli** [comment]
Did you figure out how to get this working clean? I can't even get the window to pop open at all. The documentation is very bad. Any example code would be super helpful.

**Comment by HuakunShen** [comment]
I didn't spend time on this. I personally used https://www.shadcn-vue.com/docs/components/command.html
which is based on radix-vue's comboox (https://www.radix-vue.com/components/combobox.html#combobox).

This one requires you to configure all the styling before you can see a nice UI.

This repo is similar to the original react cmdk https://github.com/pacocoursey/cmdk
Only the bare bone is provided in the package. If you want some sample code, you can try looking at how the website it built.
- App.vue: https://github.com/xiaoluoboding/vue-command-palette/blob/9daf5aa2c26f33fba65d2c1de05720fe769126dd/src/App.vue
- Raycast.vue https://github.com/xiaoluoboding/vue-command-palette/blob/9daf5aa2c26f33fba65d2c1de05720fe769126dd/src/components/command/raycast/Raycast.vue

**Comment by y1324** [comment]
> 我没有花时间做这件事。我个人使用了基于 radix-vue 的 comboox （https://www.radix-vue.com/components/combobox.html#combobox） 的 https://www.shadcn-vue.com/docs/components/command.html。
> 
> 这需要您先配置所有样式，然后才能看到漂亮的 UI。
> 
> 这个仓库类似于原来的 react cmdk https://github.com/pacocoursey/cmdk 包中只提供了裸骨。如果你想要一些示例代码，你可以尝试查看它如何构建网站。
> 
> * App.vue：https://github.com/xiaoluoboding/vue-command-palette/blob/9daf5aa2c26f33fba65d2c1de05720fe769126dd/src/App.vue
> * Raycast.vue https://github.com/xiaoluoboding/vue-command-palette/blob/9daf5aa2c26f33fba65d2c1de05720fe769126dd/src/components/command/raycast/Raycast.vue

I have the same problem as you, it's so annoying
