### ISSUE TITLE
Support for configurable fuse search

### ISSUE THREAD

**Issue by tomieric** [xiaoluoboding/vue-command-palette#8]
We need to customize some content, not just the label, but others, such as content, description fields

```js
const fuseOptions = {
  threshold: 0.2,
  keys: ['label', 'content', 'description']
}
```

Therefore it is necessary to provide a configurable parameter that will reconfigure the value of `fuseOptions`

```vue
const props = defineProps({
  theme: {
    type: String,
    default: 'default'
  },
  fuseOptions: {
     type: Object,
     default: () => ({
       threshold: 0.2,
       keys: ['label']
    })
  }
})
```

**Comment by KeJunMao** [comment]
hi, `Command.Dialog` can't set `fuseOptions`, Is there any good way?

**Comment by hackoder** [comment]
@tomieric I'm curious how you are using other keys, like content and description in your example. From what I can tell, the only way to pass a value is using `data-value` on `Command.Item`, which will convert the object to a string.
